---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Install
  ansible.builtin.include_tasks: "{{ _file }}"
  vars:
    _file: "{{ lookup('first_found', _params) }}"
    _params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/tasks"
